// Content rendered inside the sliding panel built by AppDrawer.tsx. Pure
// presentation — no animation/gesture logic here, so it's easy to reason
// about independently: the GoalSlot mark + wordmark up top, one row per app
// area, and the signed-in user's name/email + a logout action pinned at the
// bottom (mirroring the profile block already on the Settings screen).
//
// This is the direct fix for the user feedback that prompted this work —
// "I can't see notes. There is no way for me to easily go through all the
// different areas. Should have been the side task bar sidebar." — so every
// one of the app's nine screens gets a row here, not just the five that fit
// the tab bar (see app/(app)/_layout.tsx for why those five stayed on the
// physical tab bar and the rest didn't).

import { useCallback } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { useAuth } from "@/providers/auth-provider";
import { GoalSlotLogo } from "@/components/brand/GoalSlotLogo";
import { colors, radii, spacing, typography } from "@/theme/tokens";

// Closed set of real app routes, exactly mirroring the literal-union pattern
// `MORE_LINKS` already uses in app/(app)/settings.tsx — deliberately not the
// generic expo-router `Href` type, which depends on a typed-routes file
// (`.expo/types/router.d.ts`) that's only generated by running the dev
// server/bundler and isn't guaranteed to exist wherever this typechecks.
export type DrawerHref =
  | "/"
  | "/schedule"
  | "/goals"
  | "/tasks"
  | "/timer"
  | "/reports"
  | "/categories"
  | "/journal"
  | "/settings";

interface DrawerNavItem {
  href: DrawerHref;
  label: string;
  glyph: string;
}

// All nine screens. The first five match the tab bar's order; the last four
// are the ones `href: null` hides from the tab bar but that still need a
// clearly-labeled way in.
const NAV_ITEMS: DrawerNavItem[] = [
  { href: "/", label: "Today", glyph: "☀" },
  { href: "/schedule", label: "Schedule", glyph: "▤" },
  { href: "/goals", label: "Goals", glyph: "◎" },
  { href: "/tasks", label: "Tasks", glyph: "✓" },
  { href: "/timer", label: "Timer", glyph: "◷" },
  { href: "/reports", label: "Reports", glyph: "▥" },
  { href: "/categories", label: "Categories", glyph: "▦" },
  { href: "/journal", label: "Journal", glyph: "✎" },
  { href: "/settings", label: "Settings", glyph: "⚙" },
];

// "/" (Today) only matches the exact root path; every other route also
// matches its own sub-paths (e.g. deep links append `?goalId=...`, which
// keeps the same pathname, but this stays correct if a detail route is ever
// added underneath one of these in the future).
function isActiveRoute(pathname: string, href: DrawerHref): boolean {
  if (href === "/") {
    return pathname === "/";
  }
  return pathname === href || pathname.startsWith(`${href}/`);
}

export interface DrawerContentProps {
  /** Current route, from expo-router's `usePathname()` — drives the active-row highlight. */
  pathname: string;
  /** Navigate to a route and close the drawer. */
  onNavigate: (href: DrawerHref) => void;
  /** Close the drawer without navigating (✕ button). */
  onRequestClose: () => void;
}

export function DrawerContent({ pathname, onNavigate, onRequestClose }: DrawerContentProps) {
  const { user, logout } = useAuth();

  // Same confirm-before-logout UX as Settings (destructive + irreversible
  // from the user's point of view — they land back on the login screen).
  const confirmLogout = useCallback(() => {
    Alert.alert("Log out?", "You'll need to sign in again to access your schedule.", [
      { text: "Cancel", style: "cancel" },
      { text: "Log out", style: "destructive", onPress: () => void logout() },
    ]);
  }, [logout]);

  return (
    <SafeAreaView style={styles.container} edges={["top", "bottom", "left"]}>
      <View style={styles.header}>
        <GoalSlotLogo size={30} color={colors.primary} accessibilityLabel="GoalSlot" />
        <Text style={styles.wordmark}>GoalSlot</Text>
        <Pressable
          onPress={onRequestClose}
          accessibilityRole="button"
          accessibilityLabel="Close navigation menu"
          hitSlop={8}
          style={styles.closeButton}
        >
          <Text style={styles.closeGlyph}>✕</Text>
        </Pressable>
      </View>

      <ScrollView
        style={styles.nav}
        contentContainerStyle={styles.navContent}
        showsVerticalScrollIndicator={false}
      >
        {NAV_ITEMS.map((item) => {
          const active = isActiveRoute(pathname, item.href);
          return (
            <Pressable
              key={item.href}
              onPress={() => onNavigate(item.href)}
              style={[styles.navRow, active && styles.navRowActive]}
              accessibilityRole="link"
              accessibilityLabel={item.label}
              accessibilityState={{ selected: active }}
            >
              <Text style={[styles.navGlyph, active && styles.navGlyphActive]}>{item.glyph}</Text>
              <Text style={[styles.navLabel, active && styles.navLabelActive]}>{item.label}</Text>
            </Pressable>
          );
        })}
      </ScrollView>

      <View style={styles.footer}>
        <View style={styles.profileRow}>
          <View style={styles.avatar}>
            <Text style={styles.avatarInitial}>{(user?.name || user?.email || "?").charAt(0).toUpperCase()}</Text>
          </View>
          <View style={styles.profileText}>
            <Text style={styles.profileName} numberOfLines={1}>
              {user?.name || "—"}
            </Text>
            <Text style={styles.profileEmail} numberOfLines={1}>
              {user?.email || "—"}
            </Text>
          </View>
        </View>
        <Pressable
          onPress={confirmLogout}
          style={styles.logoutButton}
          accessibilityRole="button"
          accessibilityLabel="Log out"
        >
          <Text style={styles.logoutButtonText}>Log out</Text>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.card,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  wordmark: {
    ...typography.h2,
    color: colors.foreground,
    flex: 1,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: radii.full,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondary,
  },
  closeGlyph: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.mutedForeground,
  },
  nav: {
    flex: 1,
  },
  navContent: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    gap: spacing.xxs,
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    borderRadius: radii.md,
  },
  navRowActive: {
    backgroundColor: colors.secondary,
  },
  navGlyph: {
    fontSize: 18,
    width: 24,
    textAlign: "center",
    color: colors.mutedForeground,
  },
  navGlyphActive: {
    color: colors.primaryDark,
  },
  navLabel: {
    ...typography.body,
    color: colors.foreground,
  },
  navLabelActive: {
    fontWeight: "700",
    color: colors.foreground,
  },
  footer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitial: {
    color: colors.primaryForeground,
    fontSize: 16,
    fontWeight: "700",
  },
  profileText: {
    flex: 1,
    gap: spacing.xxs,
  },
  profileName: {
    ...typography.title,
    color: colors.foreground,
  },
  profileEmail: {
    ...typography.bodySmall,
    fontWeight: "400",
    color: colors.mutedForeground,
  },
  logoutButton: {
    minHeight: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: radii.md,
    backgroundColor: colors.destructiveMuted,
  },
  logoutButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.destructive,
  },
});
