// Content rendered inside the sliding panel built by AppDrawer.tsx. Pure
// presentation — no animation/gesture logic here, so it's easy to reason
// about independently: brand header, grouped nav, signed-in user + logout
// pinned at the bottom.
//
// This is the direct fix for the user feedback that prompted this work —
// "I can't see notes. There is no way for me to easily go through all the
// different areas. Should have been the side task bar sidebar." — so every
// one of the app's screens gets a row here, not just the five that fit the
// tab bar (see app/(app)/_layout.tsx for why those five stayed on the
// physical tab bar and the rest didn't).
//
// Structure is ported from web's `app-sidebar.tsx`, which is the real
// product sidebar this is standing in for:
//   - SidebarHeader: brand mark + wordmark on a bordered header band
//     (app-sidebar.tsx:141 — `border-b border-zinc-200 p-4`).
//   - SidebarGroup + SidebarGroupLabel: the nav is GROUPED, not one flat
//     list of eleven rows. The groups aren't invented here either — they're
//     the pairs app-sidebar.tsx:56-66 already documents in comments
//     ("Planning pair: Goals + Schedule", "Execution pair: Tasks + Time
//     Tracker", "Reflection pair: Journal + Coach", "Auxiliary surfaces"),
//     just made visible. Eleven undifferentiated rows is the thing that
//     makes a drawer read as a dump of links rather than as navigation.
//     Journal is the one row that no longer sits where web puts it — see
//     the note on NAV_GROUPS for that deliberate mobile-only divergence.
//   - SidebarMenuButton: rounded row, muted label and icon at rest; active
//     gets a zinc-100 fill, a zinc-200 border, a semibold label and a
//     brand-yellow icon (sidebar.tsx:443 `data-[active=true]:*` +
//     app-sidebar.tsx:204 `isActive && 'text-[#f2cc0d]'`).
//   - SidebarFooter: bordered footer band with the user's avatar (a
//     zinc-900 circle with a white initial, app-sidebar.tsx:288) and logout.
//
// The one mobile addition is the leading 3px brand bar on the active row:
// on a phone the drawer is dismissed and re-opened constantly, so "where am
// I" needs to survive a glance, and a fill alone doesn't carry that at arm's
// length the way a coloured edge does.

import { useCallback, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useQuery } from "@tanstack/react-query";

import { countUnreadConversations } from "@goalslot/shared";

import { useAuth } from "@/providers/auth-provider";
import { messagingQueries } from "@/lib/queries";
import { messagingEnabled } from "@/lib/messaging-config";
import { GoalSlotLogo } from "@/components/brand/GoalSlotLogo";
import { colors, iconSize, minTouchTarget, radii, spacing, typography } from "@/theme/tokens";
import { Icon, type IconName } from "@/components/ui/Icon";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";

// Closed set of real app routes, exactly mirroring the literal-union pattern
// `MORE_LINKS` already uses in app/(app)/settings.tsx — deliberately not the
// generic expo-router `Href` type, which depends on a typed-routes file
// (`.expo/types/router.d.ts`) that's only generated by running the dev
// server/bundler and isn't guaranteed to exist wherever this typechecks.
export type DrawerHref =
  | "/"
  | "/schedule"
  | "/goals"
  | "/tasks"
  | "/timer"
  | "/reports"
  | "/categories"
  | "/journal"
  | "/notes"
  | "/messages"
  | "/mentees"
  | "/coach"
  | "/settings";

interface DrawerNavItem {
  href: DrawerHref;
  label: string;
  icon: IconName;
}

/**
 * Unread conversation count for the Messages row's badge.
 *
 * Reads the conversations query rather than fetching its own: the Messages
 * screen and the app-wide socket (useMessagingLiveUpdates in
 * app/(app)/_layout.tsx) already keep that cache current, so the drawer
 * shows whatever the app most recently knew without adding a request every
 * time the drawer opens. `enabled: messagingEnabled` keeps this inert in
 * builds with no messaging service configured, matching the nav row itself.
 */
function useUnreadMessagesCount(currentUserId: string | undefined): number {
  const conversationsQuery = useQuery({
    ...messagingQueries.conversations(),
    enabled: messagingEnabled && !!currentUserId,
  });

  if (!currentUserId || !conversationsQuery.data) return 0;
  return countUnreadConversations(conversationsQuery.data, currentUserId);
}

interface DrawerNavGroup {
  /** Uppercase group label. Omitted for the first group, which needs no heading. */
  label?: string;
  items: DrawerNavItem[];
}

// Grouping and order both follow web's `navItems` (app-sidebar.tsx:53-70).
// Timer is web's "Time Tracker" and Coach AI is web's "GoalSlot AI" — same
// screens, mobile's existing labels kept so the drawer matches the tab bar.
//
// ONE deliberate mobile-only divergence: Journal is promoted out of the
// "Reflect" pair and up beside Today, ahead of Plan. Web can leave it fourth
// because its sidebar is always on screen — depth there costs a glance. On a
// phone the drawer is closed by default, so a row in the fourth group is
// three interactions deep for a habit that only works if it's daily, and the
// tab bar has no sixth slot to give it (see app/(app)/_layout.tsx). Today +
// Journal is also a coherent unlabelled pair on its own terms: the day's
// plan and the day's reflection, the two rows a user touches every day.
// Coach AI stays in "Reflect" — Journal is the daily habit; Coach is a thing
// you go to when you want it — which keeps the labelled groups reading
// Plan -> Do -> Reflect, the same sequence as the header tagline.
const NAV_GROUPS: DrawerNavGroup[] = [
  {
    items: [
      { href: "/", label: "Today", icon: "today" },
      { href: "/journal", label: "Journal", icon: "journal" },
    ],
  },
  {
    label: "Plan",
    items: [
      { href: "/goals", label: "Goals", icon: "goals" },
      { href: "/schedule", label: "Schedule", icon: "schedule" },
    ],
  },
  {
    label: "Do",
    items: [
      { href: "/tasks", label: "Tasks", icon: "tasks" },
      { href: "/timer", label: "Timer", icon: "timer" },
    ],
  },
  {
    label: "Reflect",
    // Journal used to sit here, above Coach AI — see the note on NAV_GROUPS
    // for why it now lives with Today instead.
    items: [{ href: "/coach", label: "Coach AI", icon: "coach" }],
  },
  {
    label: "Workspace",
    items: [
      { href: "/notes", label: "Notes", icon: "notes" },
      // Messaging is deployed as a separate service and is absent from
      // builds that don't point at one (see src/lib/messaging-config.ts).
      // A nav row to a screen that can only ever say "unavailable" is worse
      // than no row, so the entry is omitted rather than disabled — this is
      // a build-time constant, not per-user state, so nothing here becomes
      // conditional at runtime.
      ...(messagingEnabled
        ? ([{ href: "/messages", label: "Messages", icon: "messages" }] as DrawerNavItem[])
        : []),
      // Mentor view — people who share their progress with you. Unlike
      // Messages, this one isn't service-gated: it's built entirely on the
      // sharing directory GoalSlot's own API already serves.
      { href: "/mentees", label: "Mentees", icon: "mentees" },
      { href: "/reports", label: "Reports", icon: "reports" },
      { href: "/categories", label: "Categories", icon: "categories" },
      { href: "/settings", label: "Settings", icon: "settings" },
    ],
  },
];

// "/" (Today) only matches the exact root path; every other route also
// matches its own sub-paths (e.g. deep links append `?goalId=...`, which
// keeps the same pathname, but this stays correct if a detail route is ever
// added underneath one of these in the future).
function isActiveRoute(pathname: string, href: DrawerHref): boolean {
  if (href === "/") {
    return pathname === "/";
  }
  return pathname === href || pathname.startsWith(`${href}/`);
}

export interface DrawerContentProps {
  /** Current route, from expo-router's `usePathname()` — drives the active-row highlight. */
  pathname: string;
  /** Navigate to a route and close the drawer. */
  onNavigate: (href: DrawerHref) => void;
  /** Close the drawer without navigating (✕ button). */
  onRequestClose: () => void;
}

export function DrawerContent({ pathname, onNavigate, onRequestClose }: DrawerContentProps) {
  const { user, logout } = useAuth();
  const unreadMessages = useUnreadMessagesCount(user?.id);
  const [pendingLogout, setPendingLogout] = useState(false);

  // Same confirm-before-logout UX as Settings (destructive + irreversible
  // from the user's point of view — they land back on the login screen).
  const confirmLogout = useCallback(() => setPendingLogout(true), []);

  const displayName = user?.name?.trim() || user?.email || "Signed in";
  const avatarInitial = (user?.name || user?.email || "?").charAt(0).toUpperCase();

  return (
    <SafeAreaView style={styles.container} edges={["top", "bottom", "left"]}>
      <View style={styles.header}>
        <View style={styles.brand}>
          <GoalSlotLogo size={28} color={colors.primary} accessibilityLabel="GoalSlot" />
          <View style={styles.brandText}>
            <Text style={styles.wordmark}>GoalSlot</Text>
            {/* Web's GoalSlotBrand carries an optional tagline slot; mobile
                uses it as a quiet orientation line rather than marketing. */}
            <Text style={styles.tagline}>Plan · Do · Reflect</Text>
          </View>
        </View>
        <Pressable
          onPress={onRequestClose}
          accessibilityRole="button"
          accessibilityLabel="Close navigation menu"
          hitSlop={spacing.sm}
          style={({ pressed }) => [styles.closeButton, pressed && styles.closeButtonPressed]}
        >
          <Icon name="close" size={iconSize.md} color={colors.mutedForeground} />
        </Pressable>
      </View>

      <ScrollView
        style={styles.nav}
        contentContainerStyle={styles.navContent}
        showsVerticalScrollIndicator={false}
      >
        {NAV_GROUPS.map((group, groupIndex) => (
          <View key={group.label ?? "primary"} style={groupIndex > 0 && styles.groupSpaced}>
            {group.label ? <Text style={styles.groupLabel}>{group.label}</Text> : null}
            {group.items.map((item) => {
              const active = isActiveRoute(pathname, item.href);
              const badgeCount = item.href === "/messages" ? unreadMessages : 0;
              return (
                <Pressable
                  key={item.href}
                  onPress={() => onNavigate(item.href)}
                  style={({ pressed }) => [
                    styles.navRow,
                    active && styles.navRowActive,
                    pressed && !active && styles.navRowPressed,
                  ]}
                  accessibilityRole="link"
                  // The count belongs in the accessible name too - a screen
                  // reader user gets no benefit from a purely visual badge.
                  accessibilityLabel={
                    badgeCount > 0
                      ? `${item.label}, ${badgeCount} unread ${badgeCount === 1 ? "conversation" : "conversations"}`
                      : item.label
                  }
                  accessibilityState={{ selected: active }}
                >
                  {active ? <View style={styles.activeBar} /> : null}
                  <Icon
                    name={item.icon}
                    size={iconSize.md}
                    // app-sidebar.tsx:204 — the active icon, and only the
                    // icon, turns brand yellow. `primaryPressed` (the darker
                    // #D9B307) rather than raw #F2CC0D: a 2px yellow stroke
                    // on a near-white fill is barely visible at this size.
                    color={active ? colors.primaryPressed : colors.mutedForeground}
                  />
                  <Text style={[styles.navLabel, active && styles.navLabelActive]} numberOfLines={1}>
                    {item.label}
                  </Text>
                  {badgeCount > 0 ? (
                    // Already voiced through the row's accessibilityLabel
                    // above, so the badge itself is hidden from the a11y
                    // tree rather than read out a second time as a bare
                    // number with no context.
                    <View style={styles.badge} accessibilityElementsHidden importantForAccessibility="no-hide-descendants">
                      <Text style={styles.badgeText}>{badgeCount > 99 ? "99+" : badgeCount}</Text>
                    </View>
                  ) : null}
                </Pressable>
              );
            })}
          </View>
        ))}
      </ScrollView>

      <View style={styles.footer}>
        <View style={styles.profileRow}>
          <View style={styles.avatar}>
            <Text style={styles.avatarInitial}>{avatarInitial}</Text>
          </View>
          <View style={styles.profileText}>
            <Text style={styles.profileName} numberOfLines={1}>
              {displayName}
            </Text>
            {user?.email ? (
              <Text style={styles.profileEmail} numberOfLines={1}>
                {user.email}
              </Text>
            ) : null}
          </View>
        </View>
        <Pressable
          onPress={confirmLogout}
          style={({ pressed }) => [styles.logoutButton, pressed && styles.logoutButtonPressed]}
          accessibilityRole="button"
          accessibilityLabel="Log out"
        >
          <Icon name="logout" size={iconSize.sm} color={colors.destructive} />
          <Text style={styles.logoutButtonText}>Log out</Text>
        </Pressable>
      </View>

      <ConfirmDialog
        visible={pendingLogout}
        title="Log out?"
        description="You'll need to sign in again to access your schedule."
        confirmLabel="Log out"
        destructive
        onConfirm={() => {
          setPendingLogout(false);
          void logout();
        }}
        onCancel={() => setPendingLogout(false)}
      />
    </SafeAreaView>
  );
}

const ACTIVE_BAR_WIDTH = 3;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.card,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg, // app-sidebar.tsx SidebarHeader `p-4`
    paddingVertical: spacing.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  brand: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  brandText: {
    flex: 1,
  },
  wordmark: {
    ...typography.h1,
    color: colors.foreground,
  },
  tagline: {
    ...typography.label,
    color: colors.mutedForegroundLight,
    marginTop: spacing.xxs,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondary,
  },
  closeButtonPressed: {
    backgroundColor: colors.border,
  },
  nav: {
    flex: 1,
  },
  navContent: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  groupSpaced: {
    marginTop: spacing.xl,
  },
  groupLabel: {
    ...typography.label,
    color: colors.mutedForegroundLight, // app-sidebar.tsx SidebarGroupLabel `text-zinc-400`
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    // Web's rows are h-8 (32px); a drawer row is a primary navigation target
    // on a phone, so it takes the 44pt touch floor plus a little air.
    minHeight: minTouchTarget + 4,
    paddingHorizontal: spacing.md,
    borderRadius: radii.control,
    borderWidth: 1,
    // Transparent (not absent) so the active row's border doesn't shift the
    // label by a pixel when it appears.
    borderColor: "transparent",
    marginBottom: spacing.xxs,
  },
  navRowActive: {
    // sidebar.tsx:443 — `data-[active=true]:bg-zinc-100 border-zinc-200`.
    backgroundColor: colors.secondary,
    borderColor: colors.border,
  },
  navRowPressed: {
    backgroundColor: colors.background,
  },
  activeBar: {
    position: "absolute",
    left: 0,
    top: spacing.sm,
    bottom: spacing.sm,
    width: ACTIVE_BAR_WIDTH,
    borderTopRightRadius: ACTIVE_BAR_WIDTH,
    borderBottomRightRadius: ACTIVE_BAR_WIDTH,
    backgroundColor: colors.primary,
  },
  navLabel: {
    ...typography.body,
    color: colors.mutedForeground, // sidebar.tsx:443 resting label is `text-zinc-600`
    flex: 1,
  },
  navLabelActive: {
    fontWeight: "600", // `data-[active=true]:font-semibold`
    color: colors.foreground, // `data-[active=true]:text-zinc-900`
  },
  // Mirrors web's sidebar count badge (app-sidebar.tsx: `variant="brand"`,
  // `ml-auto h-4 text-[10px]`). The label above owns `flex: 1`, so this
  // lands at the trailing edge without needing a margin of its own.
  badge: {
    minWidth: 20,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    ...typography.caption,
    fontSize: 11,
    fontWeight: "700",
    // Brand yellow is a light fill; the count has to be dark to stay legible
    // on it, same as web's brand badge.
    color: colors.foreground,
  },
  footer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    // app-sidebar.tsx:288 — the footer avatar is zinc-900 with white text and
    // a zinc-100 ring, NOT brand yellow. Yellow here competes with the active
    // nav row, which is the one thing in the drawer that should own it.
    backgroundColor: colors.foreground,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.secondary, // `ring-2 ring-zinc-100`
  },
  avatarInitial: {
    ...typography.title,
    color: colors.white,
  },
  profileText: {
    flex: 1,
    gap: spacing.xxs,
  },
  profileName: {
    ...typography.body,
    fontWeight: "600",
    color: colors.foreground,
  },
  profileEmail: {
    ...typography.bodySmall,
    color: colors.mutedForeground,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    minHeight: minTouchTarget,
    borderRadius: radii.control,
    backgroundColor: colors.destructiveMuted,
  },
  logoutButtonPressed: {
    opacity: 0.75,
  },
  logoutButtonText: {
    ...typography.body,
    fontWeight: "600",
    color: colors.destructive,
  },
});
